### ISSUE TITLE
Problema após Instalação: "Static function setConfig() should not be abstract"

### ISSUE THREAD

**Issue by vinidade** [mundipagg/magento#171]
Olá,

Estou instalando este módulo em minha loja e, após terminar, ao abrir o admin, estou recebendo um Fatal Error
Class 'Zend_Log' not found in ....\app\code\core\Mage\Core\functions.php on line 247

Static function Mundipagg\Core\Kernel\Abstractions\AbstractModuleCoreSetup::setConfig() should not be abstract'

Minha versão do PHP é a 5.6.40. 
Já pesquisei bastante mas não consigo chegar a nenhuma conclusão.

Alguém tem alguma ideia?
Obrigado!

**Comment by ianlessa** [comment]
@vinidade , boa tarde.

Agradecemos o seu contato.
O time de suporte já está ciente do problema relatado e estaremos priorizando a análise deste o mais rápido possível.

**Comment by michelpl** [comment]
O atendimento prosseguirá através do nosso canal de suporte.
Fechando issue.

**Comment by vinidade** [comment]
Olá!
Hoje, quase um ano depois, fui tentar instalar novamente o módulo e continua com o mesmo erro.

**Comment by rafagaseo** [comment]
@vinidade no meu caso inverti as posições das chaves, perceba que no módulo do magento 2, a private key vem antes da public. 

Inverti as posições e deu certo.
