### ISSUE TITLE
Erro de instalação no Magento 1.9.3

### ISSUE THREAD

**Issue by philspbr** [mundipagg/magento#181]
Estou tentando atualizar o módulo para usar a nova API.
Aparece o seguinte erro no log de nginx na hora de instalar o módulo:

PHP Fatal error:  require_once(): Failed opening required '/usr/share/nginx/html/lib/autoload.php

Vi que no módulo existem chamadas da forma
`require_once` Mage::getBaseDir('lib') . '/autoload.php'`

No meu caso o arquivo autoload.php se encontra na pasta /lib/Varien/ e não em /lib/.
Não sei o arquivo fica em outro lugar se o Magento foi instalado na versão padrão de 1.9.3 ou através de vários upgrades (no meu caso desde 1.7).

Como posso resolver?

**Comment by GabrielDeveloper** [comment]
@philspbr boa noite, 

O arquivo requerido nas chamadas é um arquivo que disponibilizamos no pacote.

O arquivo da pasta Varien é uma classe de autoload do próprio magento e não do composer.

Pode informar como foi feita a instalação do modulo por favor?

**Comment by philspbr** [comment]
Oi Gabriel,

Baixei o zip do github e copiei os arquivos para a raiz do Magento. Dei uma olhada no arquivo de modman antes e parece que o mapeamento/estrutura e a mesmo.
Então eu vou tentar copiar o arquivo de autoload manualmente na pasta, mas achei estranho pois nunca mudei essa parte.
Olhando a estrutura padrão do Magento, vi que o arquivo normalmente se encontra na pasta /lib/Varien

https://github.com/OpenMage/magento-mirror/tree/magento-1.9/lib

Será que tem a ver com a minha versão?

**Comment by GabrielDeveloper** [comment]
@philspbr não recomendamos a intalação sem ser pelo Magento Connect.

o arquivo que deve ser baixado e é o **Mundipagg_Payment_Module-2.1.5.tgz** que se encontra no link: https://github.com/mundipagg/magento/releases/tag/2.1.5

O arquivo Autoload da pasta Varien não é o arquivo que o modulo usa, o arquivo autoload da pasta lib é gerado pelo composer.

**Comment by philspbr** [comment]
@GabrielDeveloper Instalei com o modman e tenho o mesmo error no log do nginx
"require_once(): Failed opening required '/usr/share/nginx/html/lib/autoload.php'" vindo do módulo. Vocês não podem disponibilizar o módulo do jeito padrão, sem exigir magento connect ou composer?
