### ISSUE TITLE
Problema depois da Instalação por Magento Connect - Strict Notice: Static function ...getDatabaseAccessObject() should not be abstract

### ISSUE THREAD

**Issue by vinidade** [mundipagg/magento#209]
Logo após a Instalação da versão 2.3.3 através do Magento Connect, ao tentar acessar a loja em um ambiente local, recebo a mesma mensagem que recebia há um ano:

Fatal error: Class 'Zend_Log' not found in C:\wamp64\www\srcporto\app\code\core\Mage\Core\functions.php on line 234

Analisando a mensagem, o erro acontece
no arquivo 
lib\mundipagg\ecommerce-module-core\src\Kernel\Abstractions\AbstractModuleCoreSetup.php

na linha 253
abstract public static function getDatabaseAccessObject();

Mensagem do erro:
Strict Notice: Static function Mundipagg\Core\Kernel\Abstractions\AbstractModuleCoreSetup::getDatabaseAccessObject() should not be abstract  in C:\wamp64\www\srcporto\lib\mundipagg\ecommerce-module-core\src\Kernel\Abstractions\AbstractModuleCoreSetup.php on line 253

Não faço a mínima ideia de como corrigir isso.

Estou usando uma versão totalmente limpa do Magento 1.9.4.3 e logo após a instalaçãa não consigo acessar mais nada da loja.

**Comment by michelpl** [comment]
Opa @vinidade tudo bem?
Desculpe a demora em responder.
Pode me informar qual a versão do php você está usando?

**Comment by vinidade** [comment]
> Opa @vinidade tudo bem?
> Desculpe a demora em responder.
> Pode me informar qual a versão do php você está usando?

Olá! Estava usando PHP 5.6. Após mudar para o 7 tudo funcionou normalmente.
